# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: scanner

# 禁用自动构建，因为我们已经在工作流中手动构建了
builds:
  - skip: true

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macos_
      {{- else }}{{ .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: darwin
        format: tar.gz
      - goos: linux
        format: tar.gz
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - scanner-amd64
      - scanner-arm64

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: archfish
    name: scanner
  draft: true
  prerelease: auto
  mode: append

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"